version: 2.1

workflows:
  version: 2
    build:
      jobs:
        - build:
            matrix:
              parameters:
                node_version: ["10", "12", "14"]

jobs:
  build:
    # working_directory: ~/
    docker:
      - image: node:<< parameters.node_version >>-slim
        # auth:
        #   username: $DOCKER_USER
        #   password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: test
          command: npm test
